ci: preserver exit code

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -57,6 +57,9 @@ jobs:
         run: |
           for algo in ${FILELIST}; do 
             IMAGE=$(grep '^image: ' $algo | sed 's/^image: \+//' | tr -d \'\")
-            docker pull $IMAGE || echo "Cannot pull image: $IMAGE"
+            if !docker pull $IMAGE ; then
+              echo "Cannot pull image: $IMAGE"
+              exit 1
+            fi
           done
 
